name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Create env files
      run: |
        echo "VITE_API_URL=http://localhost:4000" > frontend/.env.test
        echo "VITE_DEV_PORT=3000" >> frontend/.env.test
        echo "PORT=4000" > backend/.env.test
        echo "NODE_ENV=test" >> backend/.env.test
        echo "CORS_ORIGIN=http://localhost:3000" >> backend/.env.test

    - name: Run frontend tests
      run: npm run test --workspace=frontend
      
    - name: Run backend tests
      run: npm run test --workspace=backend
